version: '3'

services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://localhost:5432/postgres",
        "spring.datasource.username": "postgres",
        "spring.datasource.password": "postgres",
	"spring.datasource.driver-class-name": "org.postgresql.Driver",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQL10Dialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.format_sql": "true",
        "spring.jpa.show-sql": "true"
     }'
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
